[build]
  publish = "public"
  command = "npm run amp:build"

[build.environment]
  NPM_VERSION = "6.12.0"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
	baseUrl = "https://panda-program.com"
	sitemapPath = "/sitemap.xml"
	providers = [
		"google",
		"bing"
	]

[[redirects]]
from = "/posts/*/"
to = "/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/posts/*/index.html"
to = "/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/amp/posts/*/"
to = "/amp/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/amp/posts/*/index.html"
to = "/amp/posts/:splat"
status = 301
force = true
