[build]
  publish = "public"
  command = "npm run amp:build"
[build.environment]
  NPM_VERSION = "6.12.0"

[[redirects]]
from = "/posts/*/"
to = "/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/posts/*/index.html"
to = "/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/amp/posts/*/"
to = "/amp/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/amp/posts/*/index.html"
to = "/amp/posts/:splat"
status = 301
force = true
